import type { Metadata } from "next";
import { Comforter } from "next/font/google";
import "./globals.css";
// 字体
const comforter = Comforter({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comforter.className}>
        <div>
          {children}
        </div></body>
    </html>
  );
}
